### ISSUE TITLE
Error: Cannot find module 'proxy-addr'

### ISSUE THREAD

**Issue by motephyr** [adonisjs/core#1525]
## Package version
    "@adonisjs/ace": "^6.0.0",    
    "@adonisjs/core": "^5.0.0-preview-rc",    
    "@adonisjs/lucid": "^8.4.1", 

## Node.js and npm version
node v12.18.3
npm 6.14.6

## Sample Code (to reproduce the issue)
node ace make:migration users

```
✖  fatal     Error: Cannot find module 'proxy-addr'
Require stack:
- /home/mark/blog/build/config/app.js
- /home/mark/blog/node_modules/require-all/index.js
- /home/mark/blog/node_modules/@poppinss/utils/build/src/requireA
- /home/mark/blog/node_modules/@poppinss/utils/build/index.js
- /home/mark/blog/node_modules/@adonisjs/core/build/src/Ignitor/B
- /home/mark/blog/node_modules/@adonisjs/core/build/src/Ignitor/A
- /home/mark/blog/node_modules/@adonisjs/core/build/src/Ignitor/A
- /home/mark/blog/node_modules/@adonisjs/core/build/src/Ignitor/i
- /home/mark/blog/ace
    at Function.Module._resolveFilename (internal/modules/cjs/loa
    at Function.Module._load (internal/modules/cjs/loader.js:841:
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/mark/blog/config/app.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:
    at Module.require (internal/modules/cjs/loader.js:1025:19)
```

I solved the issue by adding proxy-addr to package.json.
But I think we can just include dependencies in the original package or generator.

**Comment by thetutlage** [comment]
Doesn't have to be an issue. Just install the module or use the discussions to clarify the behavior
