### ISSUE TITLE
start command does not seem to work in github adonis-api-app

### ISSUE THREAD

**Issue by Paris2020** [adonisjs/core#1600]
In `package.json` file:
```
 "scripts": {
    "start": "node server.js",
    "test": "node ace test",
  },
```

On cmd:
```
➜  adonis-api-app git:(master) npm start

> adonis-api-app@4.1.0 start /Users/nellymoseki/github/translations-api/adonis-api-app
> node server.js

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@adonisjs/ignitor'
Require stack:
- /Users/nellymoseki/github/translations-api/adonis-api-app/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nellymoseki/github/translations-api/adonis-api-app/server.js:20:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/nellymoseki/github/translations-api/adonis-api-app/server.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adonis-api-app@4.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adonis-api-app@4.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nellymoseki/.npm/_logs/2020-09-15T15_52_03_478Z-debug.log```

**Comment by thetutlage** [comment]
Have you run `npm install`? It seems like packages are missing. Also please use [discussions](https://github.com/adonisjs/core/discussions) and only open issues when something is confirmed as a bug
