### ISSUE TITLE
Seeding results in UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by TheRealD00dle** [adonisjs/core#1602]
## Problem description
Running seeder results in below terminal output

Other details:
* Fresh install of AdonisJS
* Migration works fine.
* Instantiating a model in a route closure and `.save()`'ing it works fine.
* MySQL Ver 8.0.19 for osx10.15 on x86_64 (Homebrew)

```bash
node ace db:seed -i
❯ Select files to run · database/seeders/customer/Status
❯ completed database/seeders/customer/Status
(node:25147) UnhandledPromiseRejectionWarning: Error: aborted
    at PendingOperation.abort (/Users/*/*/*/*/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /Users/*/*/*/*/node_modules/tarn/dist/Pool.js:203:25
    at Array.map (<anonymous>)
    at /Users/*/*/*/*/node_modules/tarn/dist/Pool.js:202:53
    at Connection.disconnect (/Users/*/*/*/*/node_modules/@adonisjs/lucid/build/src/Connection/index.js:297:17)
    at ConnectionManager.close (/Users/*/*/*/*/node_modules/@adonisjs/lucid/build/src/Connection/Manager.js:186:13)
    at async Promise.all (index 1)
    at ConnectionManager.closeAll (/Users/*/*/*/*/node_modules/@adonisjs/lucid/build/src/Connection/Manager.js:197:9)
    at DbSeed.handle (/Users/*/*/*/*/node_modules/@adonisjs/lucid/build/commands/DbSeed.js:145:9)
    at Kernel.runCommand (/Users/*/*/*/*/node_modules/@adonisjs/ace/build/src/Kernel/index.js:236:26)
    at AppCommands.handle (/Users/*/*/*/*/node_modules/@adonisjs/core/build/src/Ignitor/Ace/AppCommands.js:154:9)
    at Ace.handle (/Users/*/*/*/*/node_modules/@adonisjs/core/build/src/Ignitor/Ace/index.js:148:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:25147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Package version
5.0.0-preview-rc-1.12

## Node.js and npm version
Node: v14.8.0
NPM: 6.14.7

## Sample Code (to reproduce the issue)
```typescript
// app/Models/base/Status.ts

import { DateTime } from 'luxon'
import { BaseModel, column } from '@ioc:Adonis/Lucid/Orm'

export default class Status extends BaseModel {
    @column({ isPrimary: true })
    public id: number

    @column()
    public title: string

    @column()
    public description: string

    @column.dateTime({ autoCreate: true })
    public createdAt: DateTime

    @column.dateTime({ autoCreate: true, autoUpdate: true })
    public updatedAt: DateTime
}
```
```typescript
// database/migrations/customer/00002_status.ts

import BaseSchema from '@ioc:Adonis/Lucid/Schema'

export default class Status extends BaseSchema {
  protected tableName = 'status'

  public async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.increments('id')
      table.string('title').notNullable()
      table.string('description').notNullable()
      table.timestamps()
    })
  }

  public async down() {
    this.schema.dropTable(this.tableName)
  }
}
```
```typescript
// database/seeders/customer/Status.ts

import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import StatusModel from 'App/Models/base/Status'

export default class Status extends BaseSeeder {
  public async run() {
    // Write your database queries inside the run method
    StatusModel.createMany([
      {
        id: 1,
        title: 'To do',
        description: 'Lorem ipsum'
      },
      {
        id: 2,
        title: 'In Progress',
        description: 'Lorem ipsum'
      },
      {
        id: 3,
        title: 'Done',
        description: 'Lorem ipsum'
      }
    ])
  }
}
```

**Comment by thetutlage** [comment]
You need to use the `await` keyword since `StatusModel.createMany` is an async method.

```ts
await StatusModel.createMany([])
```

Also, make sure to use the [discussions](https://github.com/adonisjs/core/discussions) and only create issues when something is confirmed as a bug
