### ISSUE TITLE
TypeError: createDebug.load is not a function

### ISSUE THREAD

**Issue by nadir1122** [adonisjs/core#1834]
I am facing this error, due to this error, I am unable to see any compiled view output. 
Any solution to this?
This error trail is not giving me any hint of any issue in project code. seems to be pure module error
I have required this load function anywhere, however, i have used async and await calls in my code after which this seems to occur.

TypeError: createDebug.load is not a function
    at setup (D:\NodeJsProjects\AdonisProject\node_modules\knex\node_modules\debug\src\common.js:261:33)
    at Object.<anonymous> (D:\NodeJsProjects\AdonisProject\node_modules\knex\node_modules\debug\src\node.js:236:37)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\NodeJsProjects\AdonisProject\node_modules\knex\node_modules\debug\src\index.js:9:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)

**Comment by nadir1122** [comment]
const ad= await AddonModule.findBy('name', addon_name)
above line causes problem, I am not sure why

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
