### ISSUE TITLE
TypeError: createDebug.load is not a function

### ISSUE THREAD

**Issue by nadir1122** [adonisjs/core#1866]
*Delete the above section and the instructions in the sections below before submitting*

## Package version
latest

## Node.js and npm version
lastest

## Sample Code (to reproduce the issue)
  const run = async () => {
   // const isa= await this.isactive('Nexalt')
   await files.forEach(async (file) => {
      var fname="../addons/currency/"+file
      var addon=require(fname)
      var inf=addon.info()
      var addon_name=inf.name
      //const isa= await this.isactive(addon_name)
      const ad= await AddonModule.findBy('name', addon_name)
      var active=false
      if(ad)
      {
        active=true
      }

      inf.active=active
     list.push(inf)

    });

  };
 await run()

 

The above code produces the following error

TypeError: createDebug.load is not a function
at setup (D:\NodeJsProjects\AdonisProject\node_modules\knex\node_modules\debug\src\common.js:261:33)
at Object. (D:\NodeJsProjects\AdonisProject\node_modules\knex\node_modules\debug\src\node.js:236:37)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object. (D:\NodeJsProjects\AdonisProject\node_modules\knex\node_modules\debug\src\index.js:9:19)
at Module._compile (internal/modules/cjs/loader.js:1137:30)

I deleted Modules and reinstalled but no use

**Comment by RomainLanz** [comment]
Hey! 👋 

Your issue do not follow our guidelines.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [Github Discussion](https://github.com/adonisjs/core/discussions)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by nadir1122** [comment]
@RomainLanz  are you drunk or stupid?

**Comment by RomainLanz** [comment]
Thanks for your contribution!

Next time, respect us and our time and create a proper issue.
