### ISSUE TITLE
Test request redirected to "/" when validator fails

### ISSUE THREAD

**Issue by TiagoGouvea** [adonisjs/core#1916]
## Package version
```
    "@adonisjs/ace": "^5.0.8",
    "@adonisjs/ally": "^2.1.3",
    "@adonisjs/antl": "^2.0.7",
    "@adonisjs/auth": "^3.1.0",
    "@adonisjs/bodyparser": "^2.0.5",
    "@adonisjs/cli": "^4.0.12",
    "@adonisjs/cors": "^1.0.7",
    "@adonisjs/fold": "^4.0.9",
    "@adonisjs/framework": "^5.0.9",
    "@adonisjs/ignitor": "^2.0.8",
    "@adonisjs/lucid": "^6.1.3",
    "@adonisjs/session": "^1.0.27",
    "@adonisjs/shield": "^1.0.8",
    "@adonisjs/validator": "^5.0.6",
    "@adonisjs/vow": "^1.0.17",
```

## Node.js and npm version
* Node 15.1.0

## Sample Code (to reproduce the issue)

I'm using the following code to test an endpoint, to check that it will return 400 when sending an invalid JSON:

```
test('refuse invalid data', async ({ client }) => {
  const response = await client.post('skill').loginVia(adminUser).send(invalidData).end();
  response.assertStatus(400);
});

```

The route declaration:

```
Route.resource('skill', 'SkillController')
  .middleware(['auth', 'admin'])
  .validator(
    new Map([
      [['skill.store'], ['SkillStore']],
      [['skill.update'], ['SkillStore']]
    ])
  )
  .apiOnly();
```

But when I ran the test it seems to send the post, receive the validation error (it logs the exception) and redirect to "/", and the test fail with status 404 (I have no routes on "/"). The whole test:

```
yarn test -f test/functional/skill.spec.js
yarn run v1.22.4
$ adonis test -f test/functional/skill.spec.js
info: serving app on http://127.0.0.1:4000

  Skill
ExceptionHandler.handle ValidationException: E_VALIDATION_FAILED: Validation failed
    at Function.validationFailed (/Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/validator/src/Exceptions/index.js:21:19)
    at ValidatorMiddleware._runValidations (/Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/validator/src/Middleware/Validator.js:148:34)
    at async ValidatorMiddleware.handle (/Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/validator/src/Middleware/Validator.js:228:22)
    at async Admin.handle (/Users/tiagogouvea/www/carers/api/app/Middleware/Admin.js:19:5)
    at async Auth.handle (/Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/auth/src/Middleware/Auth.js:127:5)
    at async ConvertEmptyStringsToNull.handle (/Users/tiagogouvea/www/carers/api/app/Middleware/ConvertEmptyStringsToNull.js:16:5)
    at async Shield.handle (/Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/shield/src/Shield/index.js:417:5)
    at async AuthInit.handle (/Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/auth/src/Middleware/AuthInit.js:60:5)
    at async SessionMiddleware.handle (/Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/session/src/Session/Middleware.js:76:5)
    at async BodyParser.handle (/Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/bodyparser/src/BodyParser/index.js:284:7) {
  messages: [
    {
      message: 'required validation failed on title',
      field: 'title',
      validation: 'required'
    }
  ]
}
(node:20492) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
Skipped rollbar log
ExceptionHandler.handle HttpException: E_ROUTE_NOT_FOUND: Route not found GET /
    at Server._getRoute (/Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/framework/src/Server/index.js:146:13)
    at /Users/tiagogouvea/www/carers/api/node_modules/@adonisjs/framework/src/Server/index.js:429:28
ApiResponse {
  _assert: Assertion { _planned: 0, _ran: 0 },
  headers: {
    'content-type': 'text/plain; charset=utf-8',
    'content-length': '55',
    date: 'Tue, 17 Nov 2020 10:15:14 GMT',
    connection: 'close'
  },
  _cookieString: '',
  _cookies: null,
  _plainCookies: null,
  _res: <ref *1> Response {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      text: 'HttpException: E_ROUTE_NOT_FOUND: Route not found GET /',
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 8,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _enableHttp2: false,
      _agent: false,
      method: 'GET',
      url: 'http://127.0.0.1:4000/',
      _header: [Object],
      header: [Object],
      writable: true,
      _redirects: 1,
      _maxRedirects: 5,
      cookies: '',
      qs: {},
      _query: [],
      qsRaw: [],
      _redirectList: [Array],
      _streamRequest: false,
      _data: null,
      protocol: 'http:',
      host: '127.0.0.1:4000',
      _endCalled: true,
      _callback: [Function (anonymous)],
      _fullfilledPromise: [Promise],
      res: [IncomingMessage],
      req: [ClientRequest],
      _resBuffered: true,
      response: [Circular *1],
      called: true,
      [Symbol(kCapture)]: false
    },
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET / HTTP/1.1\r\n' +
        'Host: 127.0.0.1:4000\r\n' +
        'accept-encoding: gzip, deflate\r\n' +
        'user-agent: node-superagent/4.1.0\r\n' +
        'cookie: adonis-session=74607fdd9f82c9768b06a6ee0625e027ERiDu7Dx6dLh/IpHuaxlioooqofMeLl1bQGqyaNE4dZGQSdpRuOFLZwkLTNKYVFcD0inXH9NDJrpETPGGdiHL8y5S6/91HRtWy31qJ0yKczsirQKti67hnFWG3NV3TsJ; adonis-session-values=0021fbf071b698e1dd21513fa10b4e1dpaSZYjZ/PGUib1ayo7QgUSjn2f2IOQzWAUNdHy+UzAnsqg7xyP+KFZv8fxPtkhX6xog6iXkuzgkZkQI9SDC0uHRo3wSwr2JqS5VZU65UdZzf6khygneNDDl2rOxaCvdZh3X3raqFrXeHYG7jHb2NPg==\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    text: 'HttpException: E_ROUTE_NOT_FOUND: Route not found GET /',
    body: {},
    files: undefined,
    buffered: true,
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'content-length': '55',
      date: 'Tue, 17 Nov 2020 10:15:14 GMT',
      connection: 'close'
    },
    header: {
      'content-type': 'text/plain; charset=utf-8',
      'content-length': '55',
      date: 'Tue, 17 Nov 2020 10:15:14 GMT',
      connection: 'close'
    },
    statusCode: 404,
    status: 404,
    statusType: 4,
    info: false,
    ok: false,
    redirect: false,
    clientError: true,
    serverError: false,
    error: Error: cannot GET / (404)
        at Response.toError (/Users/tiagogouvea/www/carers/api/node_modules/superagent/lib/node/response.js:94:15)
        at ResponseBase._setStatusProperties (/Users/tiagogouvea/www/carers/api/node_modules/superagent/lib/response-base.js:123:16)
        at new Response (/Users/tiagogouvea/www/carers/api/node_modules/superagent/lib/node/response.js:41:8)
        at Request._emitResponse (/Users/tiagogouvea/www/carers/api/node_modules/superagent/lib/node/index.js:850:20)
        at IncomingMessage.<anonymous> (/Users/tiagogouvea/www/carers/api/node_modules/superagent/lib/node/index.js:1036:38)
        at IncomingMessage.emit (node:events:339:22)
        at endReadableNT (node:internal/streams/readable:1289:12)
        at processTicksAndRejections (node:internal/process/task_queues:80:21) {
      status: 404,
      text: 'HttpException: E_ROUTE_NOT_FOUND: Route not found GET /',
      method: 'GET',
      path: '/'
    },
    created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: true,
    unprocessableEntity: false,
    type: 'text/plain',
    charset: 'utf-8',
    links: {},
    setEncoding: [Function: bound ],
    redirects: [ 'http://127.0.0.1:4000/' ],
    pipe: [Function (anonymous)],
    [Symbol(kCapture)]: false
  }
}
undefined
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /
{}
    ✖ refuse invalid data (141ms)


   ERRORS

  1. refuse invalid data
  expected 404 to equal 400
  404 => 400

   FAILED
```

The test suite, also send a valid data, list records, delete the new record, and all works fine. One **working sample** test in same suite:

```
test('Create new skill', async ({ assert, client }) => {
  const response = await client.post('/skill').loginVia(adminUser).send(postData).end();
  assert.isObject(response.body);
  response.assertStatus(200);
  response.assertJSONSubset(postData);
});
```

- When calling the route by Postman, it works like expected, return the validation errors and show it (I'm not redirected)
- It's just falling when the validator throws the exception
- I haven't any middleware or code that do redirects

**Comment by TiagoGouvea** [comment]
Trying here to find if it's my fault, I see that my ExceptionHandler was returning:

```
return super.handle(...arguments);
``` 
I changed to

```
return response.status(error.status).send(error.message);
```

Changing to this kind of return solved the thing.

I will close the issue because it's not a bug. But, the tests on the console get different status from Postman because, seems to be a `BaseExceptionHandler` behavior.

**Comment by diegogit03** [comment]
solved? i have this problem

**Comment by RomainLanz** [comment]
> solved? i have this problem

Ensure to use the correct header to tell Adonis to send you back JSON.
