### ISSUE TITLE
Adonis v5 can't run npm start

### ISSUE THREAD

**Issue by GabrielGomesBarbosa** [adonisjs/core#2623]
I create a new project using this command `npm init adonis-ts-app@latest <my-project-name>`, i dind't edit any files, just run `npm run start`.

My output:

```
$ npm run start

> adonisdocker@1.0.0 start C:\Users\gabri\Documents\Projects Lesson\Node\adonisdocker
> node server.js

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'C:\Users\gabri\Documents\Projects Lesson\Node\adonisdocker\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adonisdocker@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adonisdocker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gabri\AppData\Roaming\npm-cache\_logs\2021-05-15T20_24_05_782Z-debug.log
```

## Package version
```
{
  "name": "adonisdocker",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build --production",
    "start": "node server.js",
    "dev": "node ace serve --watch",
    "lint": "eslint . --ext=.ts"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^5.2.0",
    "adonis-preset-ts": "^2.1.0",
    "eslint": "^7.26.0",
    "eslint-plugin-adonis": "^1.3.1",
    "pino-pretty": "^4.8.0",
    "typescript": "^4.2.4",
    "youch": "^2.2.2",
    "youch-terminal": "^1.1.1"
  },
  "dependencies": {
    "@adonisjs/core": "^5.1.6",
    "@adonisjs/repl": "^3.1.2",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
}
```

## Node.js and npm version
Node: 14.17.0
Npm: 6.14.13

## Sample Code (to reproduce the issue)
Create a new project and execute `npm run start`

**Comment by RomainLanz** [comment]
Hey @GabrielGomesBarbosa! 👋 

This command should be used for **production** only (after the build of your code). Use `npm run dev` to run your code in development.
