### ISSUE TITLE
i just started using adonis, But it say ...

### ISSUE THREAD

**Issue by KimhoutSam** [adonisjs/core#2930]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Package version
^5.1.9

## Node.js and npm version
node: v14.17.0 | npm: 7.10.0

## Sample Code (to reproduce the issue)
```bash
(node:11019) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/jeremykimhoutsam/Documents/CodeWorkspace/Study/AdonisApi/server.ts:13
import 'reflect-metadata'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

## BONUS (a sample repo to reproduce the issue)
https://github.com/KimhoutSam/adonisapi

**Comment by teamsoo** [comment]
Same issue here

### ENV
```
Node 16.5.0
npm 7.19.1
```

### FRESH HELLO WORLD PROJECT
`npm init adonis-ts-app@latest hello-world`

### RESULT
```
    _       _             _         _     
   / \   __| | ___  _ __ (_)___    | |___ 
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/


CUSTOMIZE PROJECT
❯ Select the project structure · web
❯ Enter the project name · hello-world
❯ Setup eslint? (y/N) · true
❯ Setup prettier? (y/N) · true
❯ Configure webpack encore for compiling frontend assets? (y/N) · true

RUNNING TASKS
❯ Scaffold project 68 ms
❯ Install dependencies 34 s
❯ Configure installed packages 2.75 s
❯ Configure webpack encore 28 s

[ success ]  Project created successfully

╭─────────────────────────────────────────────────╮
│    Run following commands to get started        │
│─────────────────────────────────────────────────│
│                                                 │
│    ❯ cd hello-world                             │
│    ❯ node ace serve --watch                     │
│                                                 │
╰─────────────────────────────────────────────────╯
```

### FIRST RUN
`node ace serve --watch`

### ERROR RESULT
```
[ info ]  building project...
[ info ]  starting http server...
(node:35289) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/xxx/Workspace/xxx/adonis/hello-world/server.ts:13
import 'reflect-metadata'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
[ encore ] Running webpack-dev-server ...
[ warn ]  Underlying HTTP server died with "1 code"
[ info ]  watching file system for changes
[ encore ] [webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.client has an unknown property 'host'. These properties are valid:
   object { logging?, overlay?, progress?, webSocketTransport?, webSocketURL? }
[ warn ]  Underlying encore dev server died with "2 code"
```

**Comment by SerjoA** [comment]
already answered

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/assembler/releases/tag/v5.3.4
