### ISSUE TITLE
how to upload file to firebase ?i tried new docs and old docs too cannot upload.

### ISSUE THREAD

**Issue by ibalaji777** [adonisjs/core#2955]
i did as per adonis documentation
i am getting error bytelength

my client side code

```
let formData = new FormData()
formData.append('file',  this.files)
console.log(formData)
      let url = 'admin/media'
      let config = {
	headers: {
          'content-type': 'multipart/form-data'
	}
      }
 var result=     await this.$axios({
      	method: 'post',
      	url: url,
      	data:  formData,
      	config: config
      })

```
my bucket code is simple , i am calling after my firebase credential initalize.
  **var storageRef =await firebase.storage().ref('img/test.jpg');
  var task =await storageRef.put(payload.file);**

method 1: i tried
```
 const postSchema = schema.create({
    file: schema.file({
      size: '2mb',
      extnames: ['jpg', 'gif', 'png'],
    }),
  })

  const payload = await request.validate({ schema: postSchema })
  var storageRef =await firebase.storage().ref('img/test.jpg');
  var task =await storageRef.put(payload.file);



```
Getting error:
```

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'byteLength' of undefined
    at C:\WinNMP\WWW\angalware_cloud\server\node_modules\@firebase\storage\src\implementation\blob.ts:118:30
    at Array.forEach (<anonymous>)
    at Function.FbsBlob.getBlob (C:\WinNMP\WWW\angalware_cloud\server\node_modules\@firebase\storage\src\implementation\blob.ts:117:19)
    at multipartUpload (C:\WinNMP\WWW\angalware_cloud\server\node_modules\@firebase\storage\src\implementation\requests.ts:332:24)
    at C:\WinNMP\WWW\angalware_cloud\server\node_modules\@firebase\storage\src\task.ts:332:27
    at C:\WinNMP\WWW\angalware_cloud\server\node_modules\@firebase\storage\src\task.ts:185:11
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
(node:17964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

i tried s3 cloud

```
const file = request.file('file', {
  size: '2mb',
  extnames: ['jpg', 'png', 'gif'],
})

const fileName = `${cuid()}.${file.extname}`
  var storageRef =await firebase.storage().ref('img/test.jpg');
  var task =await storageRef.put(fs.createReadStream(file.tmpPath));
```

getting same error strange what is the problem i tried all the ways but not working anything but same thing i did in nuxt it uploads smoothly.

**Comment by thetutlage** [comment]
This is more of a question and not a bug with the framework. Please use [discussions](https://github.com/adonisjs/core/discussions) for asking questions

**Comment by ibalaji777** [comment]
i tried many ways but still getting same problem ,please can u suggest any  blog or similar issue on github.

**Comment by RomainLanz** [comment]
It does not matter, this a question and not an issue with the framework itself.

Please, create a new thread inside GitHub Discussion to get any help.
