### ISSUE TITLE
csrfField method not found & csrfToken undefined

### ISSUE THREAD

**Issue by moatazHajres** [adonisjs/core#3035]
## adonis version
@latest

## Node.js and npm version
npm : 6.14.8
node: 14.15.2

trying to call {{csrfField()}} inside a form in a edge template, gives me a 500 error with a "csrfField is not a function"
and also {{csrfToken}} gives undefined.

## note that I installed & configured adonis shield.

error log in console : 
`[1628806309859] ERROR (hello/10768 on Motile-M142): csrfField is not a function
    err: {
      "type": "EdgeError",
      "message": "csrfField is not a function",
      "stack":
          Error: csrfField is not a function
              at anonymous (C:\wamp64\www\hello-adonis\hello\resources\views\users\create.edge:14:0)
              at Template.reThrow (C:\wamp64\www\hello-adonis\hello\node_modules\edge.js\build\src\Template\index.js:178:15)
              at template (eval at wrapToFunction (C:\wamp64\www\hello-adonis\hello\node_modules\edge.js\build\src\Template\index.js:64:20), <anonymous>:107:10)
              at Template.renderCompiled (C:\wamp64\www\hello-adonis\hello\node_modules\edge.js\build\src\Template\index.js:84:57)    
              at Template.render (C:\wamp64\www\hello-adonis\hello\node_modules\edge.js\build\src\Template\index.js:139:21)
              at EdgeRenderer.render (C:\wamp64\www\hello-adonis\hello\node_modules\edge.js\build\src\Renderer\index.js:37:103)       
              at Edge.render (C:\wamp64\www\hello-adonis\hello\node_modules\edge.js\build\src\Edge\index.js:233:35)
              at UsersController.create (C:\wamp64\www\hello-adonis\hello\app\Controllers\Http\UsersController.ts:14:17)
              at Injector.callAsync (C:\wamp64\www\hello-adonis\hello\node_modules\@adonisjs\fold\build\src\Ioc\Injector.js:124:30)   
      "code": "E_RUNTIME_EXCEPTION",
      "line": 14,
      "col": 0,
      "filename": "C:\\wamp64\\www\\hello-adonis\\hello\\resources\\views\\users\\create.edge",
      "status": 500
    }`

**Comment by moatazHajres** [comment]
turned out that that I should use ctx.view.render instead of View.render to be able to use {{csrfField()}} in the rendered edge view.
