### ISSUE TITLE
TypeError: No hash found in the given string

### ISSUE THREAD

**Issue by aleksadjukic** [adonisjs/core#3078]
### Discussed in https://github.com/adonisjs/core/discussions/3076

<div type='discussions-op-text'>

<sup>Originally posted by **aleksadjukic** August 22, 2021</sup>
I'm making an API authentication system and I'm successfully registering users and **hashing they're passwords** using the Hash module with a @beforeSave() hook, but when I try to log a user in with:

`await auth.use('api').attempt(email, password)`

I get a **no hash found in the given string** error. I tried switching from argon to bcrypt but I still get the same error.
The email and password both are valid strings and have values at the point of passing them into the **attempt** method.

Here is a complete error object: 

`   err: {
      "type": "TypeError",
      "message": "No hash found in the given string",
      "stack":
          TypeError: No hash found in the given string
              at Object.verify (C:\Users\YT\Desktop\api\node_modules\phc-bcrypt\index.js:164:27)
              at Bcrypt.verify (C:\Users\YT\Desktop\api\node_modules\@adonisjs\hash\build\src\Drivers\Bcrypt.js:39:37)
              at Hash.verify (C:\Users\YT\Desktop\api\node_modules\@adonisjs\hash\build\src\Hash\index.js:116:27)
              at LucidUser.verifyPassword (C:\Users\YT\Desktop\api\node_modules\@adonisjs\auth\build\src\UserProviders\Lucid\User.js:52:23)
              at OATGuard.verifyPassword (C:\Users\YT\Desktop\api\node_modules\@adonisjs\auth\build\src\Guards\Base\index.js:78:45)
              at OATGuard.verifyCredentials (C:\Users\YT\Desktop\api\node_modules\@adonisjs\auth\build\src\Guards\Base\index.js:134:20)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
              at OATGuard.attempt (C:\Users\YT\Desktop\api\node_modules\@adonisjs\auth\build\src\Guards\Oat\index.js:204:22)
              at AuthController.login (C:\Users\YT\Desktop\api\app\Controllers\Http\AuthController.ts:23:19)
              at Object.PreCompiler.runRouteHandler [as fn] (C:\Users\YT\Desktop\api\node_modules\@adonisjs\http-server\build\src\Server\PreCompiler\index.js:47:31)     "status": 500
    }` 
</div>

**Comment by aleksadjukic** [comment]
Solution here: [#3076](https://github.com/adonisjs/core/discussions/3076)
