### ISSUE TITLE
In Adonis 4.1.0 getting these error while running migation.

### ISSUE THREAD

**Issue by AliZaibazr** [adonisjs/core#3335]
TypeError: Cannot read property 'apply' of undefined
    at SchemaCompiler_MySQL.toSQL (D:\server\node_modules\@adonisjs\lucid\node_modules\knex\lib\schema\compiler.js:72:26)
    at SchemaBuilder.toSQL (D:\server\node_modules\@adonisjs\lucid\node_modules\knex\lib\schema\builder.js:79:43)        
    at D:\server\node_modules\@adonisjs\lucid\node_modules\knex\lib\runner.js:31:36
    at D:\server\node_modules\@adonisjs\lucid\node_modules\knex\lib\runner.js:277:24

I tried with alternative versions of dependencies but can't resolved,
Thanks.

**Comment by thetutlage** [comment]
The issue should be reported with the Lucid repo. Also, please provide complete details including the lucid package version and the migration file code for anyone to help.
