### ISSUE TITLE
package Got error ES Module

### ISSUE THREAD

**Issue by arnauddoub** [adonisjs/core#3914]
## Package version
```json
"@adonisjs/assembler": "^5.8.1",
"@adonisjs/core": "^5.8.6",
"@adonisjs/repl": "^3.1.11",
```

## Node.js and npm version
node v16.15.0, npm 8.5.5

## Sample Code (to reproduce the issue)
I installed `got` but when I try to use it I get the following error:

```json
{
"message": "require() of ES Module /Sites/simulimmo/simulimmo-api/node_modules/.pnpm/got@12.5.0/node_modules/got/dist/source/index.js from /Sites/simulimmo/simulimmo-api/app/Controllers/Http/RentController.ts not supported.\nInstead change the require of index.js in /Sites/simulimmo/simulimmo-api/app/Controllers/Http/RentController.ts to a dynamic import() which is available in all CommonJS modules.",
"stack": "Error [ERR_REQUIRE_ESM]: require() of ES Module /Sites/simulimmo/simulimmo-api/node_modules/.pnpm/got@12.5.0/node_modules/got/dist/source/index.js from /Sites/simulimmo/simulimmo-api/app/Controllers/Http/RentController.ts not supported.\nInstead change the require of index.js in /Sites/simulimmo/simulimmo-api/app/Controllers/Http/RentController.ts to a dynamic import() which is available in all CommonJS modules.\n    at Object.<anonymous> (/Sites/simulimmo/simulimmo-api/app/Controllers/Http/RentController.ts:6:31)\n    at Module._compile (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:136:24)\n    at Object.newLoader [as .ts] (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:141:7)\n    at ImportAliases.resolve (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/@adonisjs+fold@8.2.0/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js:99:23)\n    at ImportAliases.resolveAsync (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/@adonisjs+fold@8.2.0/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js:117:25)\n    at Ioc.import (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/@adonisjs+fold@8.2.0/node_modules/@adonisjs/fold/build/src/Ioc/index.js:280:42)\n    at Ioc.makeAsync (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/@adonisjs+fold@8.2.0/node_modules/@adonisjs/fold/build/src/Ioc/index.js:391:40)\n    at IocResolver.call (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/@adonisjs+fold@8.2.0/node_modules/@adonisjs/fold/build/src/Resolver/index.js:90:47)\n    at Object.PreCompiler.runRouteHandler [as fn] (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/@adonisjs+http-server@5.11.0_wfecxmd3ufg6hfkr77uocjzjuq/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:51)\n    at Runnable.invoke (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/co-compose@7.0.2/node_modules/co-compose/build/src/Runnable.js:55:48)\n    at BodyParserMiddleware.handle (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/@adonisjs+bodyparser@8.1.6_i5xyddv3gvfvdmbrjmampe2cku/node_modules/@adonisjs/bodyparser/build/src/BodyParser/index.js:104:20)\n    at Injector.callAsync (/Sites/simulimmo/simulimmo-api/node_modules/.pnpm/@adonisjs+fold@8.2.0/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)",
"code": "ERR_REQUIRE_ESM"
}
```

**Comment by Julien-R44** [comment]
Got@12 is ESM only. You have to download version 11

**Comment by arnauddoub** [comment]
I don't really understand why it says "Human-friendly and powerful HTTP request library for Node.js" but the latest version does not work on nodejs

**Comment by RomainLanz** [comment]
It works on Node, you simply have to setup your application as ESM.
Which is not doable in AdonisJS for the moment.
