### ISSUE TITLE
AuthenticationException: E_INVALID_AUTH_SESSION: Invalid session

### ISSUE THREAD

**Issue by meshackjr** [adonisjs/core#3967]
I am getting the error 

```
[17:25:00.186] TRACE (project/1129674): Authentication failure
AuthenticationException: E_INVALID_AUTH_SESSION: Invalid session
at Function.invalidSession (/project/node_modules/@adonisjs/auth/build/src/Exceptions/AuthenticationException.js:82:16)
at SessionGuard.authenticate (/project/node_modules/@adonisjs/auth/build/src/Guards/Session/index.js:255:69)
at SessionGuard.check (/project/node_modules/@adonisjs/auth/build/src/Guards/Session/index.js:276:24)
at AuthMiddleware.authenticate (/project/app/Middleware/Auth.ts:38:33)
at AuthMiddleware.handle (/project/app/Middleware/Auth.ts:73:16)
at Injector.callAsync (/project/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
```

The user is redirected back to login page immediately after being authenticated, i have tried setting the session driver to file and i have been able to see session files being created but once its time to use them the session says its invalid.

I am using a proxy configuration on apache.

## Package version
```
"@adonisjs/auth": "^8.2.2",
"@adonisjs/core": "^5.8.6",
```

## Node.js and npm version
```
node v14.17.1
npm v8.15.0
```

## Sample Code (to reproduce the issue)
```
 await auth.use('guard').attempt(email, password)
```

**Comment by RomainLanz** [comment]
Hey @meshackjr! 👋🏻 

Have you installed the session driver?

```ts

**Comment by meshackjr** [comment]
Yes, i have installed the session driver, the application works fine on
nginx, its just on apache that is where it fails
