### ISSUE TITLE
Webpack-cli throwing error in fresh application

### ISSUE THREAD

**Issue by cmjio** [adonisjs/core#3982]
## Package version

```
  {
    "name": "encoretest",
    "version": "1.0.0",
    "private": true,
    "scripts": {
      "dev": "node ace serve --watch",
      "build": "node ace build --production",
      "start": "node server.js"
    },
    "devDependencies": {
      "@adonisjs/assembler": "^5.9.4",
      "@babel/core": "^7.17.0",
      "@babel/preset-env": "^7.16.0",
      "@japa/preset-adonis": "^1.2.0",
      "@japa/runner": "^2.2.2",
      "@symfony/webpack-encore": "^4.1.1",
      "@types/proxy-addr": "^2.0.0",
      "@types/source-map-support": "^0.5.6",
      "adonis-preset-ts": "^2.1.0",
      "pino-pretty": "^9.1.1",
      "typescript": "~4.6",
      "webpack": "5.72",
      "webpack-cli": "^4.9.1",
      "youch": "^3.2.2",
      "youch-terminal": "^2.1.5"
    },
    "dependencies": {
      "@adonisjs/core": "^5.8.9",
      "@adonisjs/repl": "^3.1.11",
      "@adonisjs/session": "^6.4.0",
      "@adonisjs/shield": "^7.1.0",
      "@adonisjs/view": "^6.2.0",
      "proxy-addr": "^2.0.7",
      "reflect-metadata": "^0.1.13",
      "source-map-support": "^0.5.21"
    }
  }
```

## Node.js and npm version
Node: v16.3.0
NPM: v8.5.0

## Sample Code (to reproduce the issue)

```
npm init adonis-ts-app@latest encoretest
// web style, encore enabled
cd encoretest
node ace serve --watch
```

This is resulting in the following error

```
node ace serve --watch
[ info ]  building project...
[ info ]  starting http server...
[14:09:49.917] INFO (encoretest/35884): started server on 0.0.0.0:51595
[ encore ] Running webpack-dev-server ...
[ info ]  watching file system for changes
╭────────────────────────────────────────────────────────╮
│                                                        │
│    Server address: http://127.0.0.1:51595              │
│    Watching filesystem for changes: YES                │
│    Encore server address: http://localhost:8080        │
│                                                        │
╰────────────────────────────────────────────────────────╯
[ encore ] [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (/Users/cmj/personal/sideprojects/encoretest/node_modules/@webpack-cli/serve/lib/index.js:146:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Users/cmj/personal/sideprojects/encoretest/node_modules/webpack-cli/lib/webpack-cli.js:1672:7)
[ warn ]  Underlying encore dev server died with "2 code"
```

**Comment by gcavanunez** [comment]
Hi, just ran into this same issue

**Comment by thetutlage** [comment]
Just run `npm update` to update the version of `webpack-cli` to version `^4.10.0`. Or manually update webpack-cli as follows.

```sh
npm i webpack-cli@4.10.0
```

> Note: Do not install `webpack-cli@5.0`, because encore does not work with Webpack CLI 5 as of now.

Also, I have fixed the AdonisJS installer to install the correct version of webpack-cli. https://github.com/adonisjs/assembler/releases/tag/v5.9.5

**Comment by gcavanunez** [comment]
Yup, running `npm update` fixes it, thanks man!
