### ISSUE TITLE
Problem to pluralize some words

### ISSUE THREAD

**Issue by ivanvinicius** [adonisjs/core#4230]
## The issue

I have a Model called Advice, and I was trying to query some records when faced the error below:

```js
// controller
const query = Nutritionist.query()
 .preload('user')
 .preload('advices')
 .orderBy('updatedAt', 'desc')
```

```cmd
error: select * from "advice" where "nutritionist_id" in ($1) - relation "advice" does not exist
    at Parser.parseErrorMessage (/home/ivan/www/cookinplus-api/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/ivan/www/cookinplus-api/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/ivan/www/cookinplus-api/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/ivan/www/cookinplus-api/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 105,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '15',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable'
}
```
So, the solution here was to set a static table name on model

```js
export default class Advice extends BaseModel {
  public static table = 'advices'
}
```

## Package version
"@adonisjs/core": "^5.8.0",
"@adonisjs/lucid": "^18.3.0",

## Node.js and npm version
Node 18.16.0
npm 9.5.1

## Sample Code (to reproduce the issue)

```js
import { string } from '@ioc:Adonis/Core/Helpers'

string.pluralize('advice') // returns singular word
string.pluralize('financé') // returns singular word
```

**Comment by RomainLanz** [comment]
Hey @ivanvinicius! 👋🏻 

The noun `advice` is a noncount noun. 

> 'Advice' is a noun meaning "an opinion or suggestion about what someone should do." Advice is a noncount noun (or mass noun) which means it does not have a plural form.

[The Britannica Dictionary](https://www.britannica.com/dictionary)(https://www.britannica.com/dictionary/eb/qa/When-to-Use-Advice-and-Advise-)

**Comment by ivanvinicius** [comment]
@RomainLanz I made a mistake about financé, actually the word is `fiancée` and comes from [english UK](https://dictionary.cambridge.org/dictionary/essential-british-english/fiancee)

By the way, thank you for the 'advice' [😊](https://emojipedia.org/smiling-face-with-smiling-eyes)
