### ISSUE TITLE
How to exit a command gracefully on `SIGINT` for Adonis v6

### ISSUE THREAD

**Issue by shiny** [adonisjs/core#4263]
# How to exit a command gracefully on `SIGINT`(press `Control + C`) for Adonis v6 ?

## Package version
`"@adonisjs/core": "^6.1.5-26"`
`"@adonisjs/redis": "^8.0.0-10"`

## Node.js and npm version
`v20.4.0`
`9.7.2`

## Sample Code (to reproduce the issue)

```typescript
import { BaseCommand } from '@adonisjs/core/ace'
import { CommandOptions } from '@adonisjs/core/types/ace'

export default class Example extends BaseCommand {
  static commandName = 'example'
  static description = ''

  static options: CommandOptions = {
    startApp: true,
    staysAlive: true,
  }

  prepare() {
    this.app.terminating(() => {
      console.log('terminating')
    })
    /**
     * if i don't listen on signal `SIGINT` to terminate the app,
     * it won't print `terminating`, means no opportunity to do a clean up
     */
    this.app.listen('SIGINT', () => this.app.terminate())
  }

  async run() {
    const redis = await this.app.container.make('redis')
    this.logger.info(await redis.ping())
    this.logger.info('Hello world from "Example"')
  }
}
```

this above code produce an error
```
node ace example
[ info ] PONG
[ info ] Hello world from "Example"
^Cterminating
terminating

/Users/daijie/Desktop/hello-world/node_modules/.pnpm/ioredis@5.3.2/node_modules/ioredis/built/redis/event_handler.js:189
        self.flushQueue(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
                        ^

Error: Connection is closed.
    at close (/Users/daijie/Desktop/hello-world/node_modules/.pnpm/ioredis@5.3.2/node_modules/ioredis/built/redis/event_handler.js:189:25)
    at Socket.<anonymous> (/Users/daijie/Desktop/hello-world/node_modules/.pnpm/ioredis@5.3.2/node_modules/ioredis/built/redis/event_handler.js:156:20)
    at Object.onceWrapper (node:events:627:26)
    at Socket.emit (node:events:512:28)
    at TCP.<anonymous> (node:net:334:12)
```

Every time I press `control + c`, to terminate app on `SIGINT`, message `terminating` would appears twice, and ioredis error occured

**Comment by thetutlage** [comment]
Hello!

This is the intended behavior. Since the commands are in control of the process, they themselves decide how to handle the termination when `SIGINT` or any other signal is received.

If you want to always kill all commands on `SIGINT`, you can modify the behavior inside `bin/console.ts` file.

https://github.com/adonisjs/slim-starter-kit/blob/main/bin/console.ts#L39-L40

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
