### ISSUE TITLE
Response Macro not found

### ISSUE THREAD

**Issue by ikollipara** [adonisjs/core#4274]
I'm using Turbo as part of Adonis, but I can't seem to extend the Response object. I followed the guidelines from the documentation, but am constantly thrown a 500 error. I've logged the response, which does receive the macro, but somehow it isn't found. I've registered the providers registered in the `AdonisRC` file, and I've added to the type definition, but I still can't access the method.

This is more frustrated as I've defined simpler macro that worked fine. Any help would be very much appreciated

## Package version
@adonisjs/core - 5.9.0

## Node.js and npm version
npm - 9.8.1
node - 18.8.2

## Sample Code (to reproduce the issue)
```js
  public async boot() {
    // All bindings are ready, feel free to use them
    type RenderedTemplate = string

    type StreamResponse = [
      'append' | 'prepend' | 'replace' | 'update' | 'remove' | 'after',
      string,
      RenderedTemplate,
    ]
    const Response = this.app.container.use('Adonis/Core/Response')

    console.log('Registered')
    Response.macro('sendStream', function (renderedValues: StreamResponse[]) {
      this.header('Content-Type', 'text/vnd.turbo-stream.html').send(
        renderedValues
          .map(
            ([action, target, renderedTemplate]) =>
              `<turbo-stream action="${action}" target="${target}"><template>${renderedTemplate}</template></turbo-stream>`
          )
          .join('\n')
      )
    })

    console.log(Response)
  }
```

```json
  "providers": [
    "./providers/AppProvider",
    "./providers/TurboStreamProvider",
    "@adonisjs/core",
    "@adonisjs/session",
    "@adonisjs/view",
    "@adonisjs/shield",
    "@adonisjs/lucid",
    "@adonisjs/bouncer",
    "@adonisjs/auth",
    "@adonisjs/attachment-lite",
    "@adonisjs/lucid-slugify",
    "@adonisjs/drive-gcs",
    "@adonisjs/drive-s3"
  ]
```

```js
 public async store({ auth, request, response, view }: HttpContextContract) {
    try {
      const { email, password } = await request.validate(LoginValidator)
      await auth.attempt(email, password)
      return response.formRedirectTo('user#index')
    } catch (error) {
      console.log(Object.getOwnPropertyNames(response))
      response.status(422).sendSteam([
        ['replace', 'email', await view.render('components/forms/invalid_email')],
        ['replace', 'password', await view.render('components/forms/invalid_password')],
      ])
    }
}
```

**Comment by thetutlage** [comment]
What's the error?

**Comment by ikollipara** [comment]
```
err: {
      "type": "TypeError",
      "message": "response.status(...).sendSteam is not a function",
      "stack":
          TypeError: response.status(...).sendSteam is not a function
              at AuthController.store (/workspaces/ubuntu-3/app/Controllers/Http/AuthController.ts:35:28)
              at Object.PreCompiler.runRouteHandler [as fn] (/workspaces/ubuntu-3/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
              at LogRequest.handle (/workspaces/ubuntu-3/app/Middleware/LogRequest.ts:7:5)
              at ShieldMiddleware.handle (/workspaces/ubuntu-3/node_modules/@adonisjs/shield/build/src/ShieldMiddleware/index.js:80:9)
              at Server.handleRequest (/workspaces/ubuntu-3/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
      "status": 500
    }
```

**Comment by thetutlage** [comment]
Because, `sendSteam` is not a function. Double check the method you have added and the one you are calling. 

Also, please use discussion forum for asking questions. The issues tracker is for tracking confirmed issues or bugs
