### ISSUE TITLE
`build` command fails when paths are passed via `--assets-args`

### ISSUE THREAD

**Issue by irshadahmad21** [adonisjs/core#4436]
### Package version

6.3.1

### Describe the bug

I am trying to create SSR [build](https://docs.adonisjs.com/guides/commands-reference#build) via vite and it fails like this

```
$ node ace build --assets-args=--"ssr=resources/js/ssr.tsx --outDir=public/assets/ssr"
[ info ] cleaning up output directory (build)
[ info ] compiling frontend assets (vite)
vite v5.1.4 building SSR bundle for production...
✓ 0 modules transformed.
x Build failed in 6ms
error during build:
RollupError: Could not resolve entry module "resources/js/ssr.tsx --outDir=public/assets/ssr".
    at error (file:///Users/projects/test/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.loadEntryModule (file:///Users/projects/test/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:18043:20)
    at async Promise.all (index 0)
```

If I change the order of arguments inside `--assets-args`, e.g. `--outDir` before other flags, like this

`node ace build --assets-args="--outDir=public/assets/ssr --ssr=resources/js/ssr.tsx"`

It treats the whole string as `outDir` and outputs the assets inside `public/assets/ssr --ssr=resources/js/ssr.tsx` directory

**Comment by irshadahmad21** [comment]
Nevermind, passing separate flags works

`node ace build --assets-args="--outDir=public/assets/ssr" --assets-args="--ssr=resources/js/ssr.tsx"`
